# Generated by Django 4.2.6 on 2024-05-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='com',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='com',
            name='year',
            field=models.IntegerField(choices=[(2022, '2022'), (2023, '2023'), (2024, '2024')]),
        ),
    ]
