# Generated by Django 4.2.6 on 2024-05-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_com_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='com',
            name='image',
            field=models.CharField(choices=[('assets/com1.jpg', 'Comisión 2022'), ('assets/com2.jpg', 'Comisión 2023'), ('assets/vinyl.png', 'Comisión 2024')], default='assets/vinyl.png', max_length=200),
        ),
    ]
