# Generated by Django 4.2.6 on 2024-05-18 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_com_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='com',
            name='image',
        ),
    ]
