# Generated by Django 4.2.6 on 2024-05-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_com_link_alter_com_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='com',
            name='image',
            field=models.CharField(choices=[(2022, 'assets/com1.jpg'), (2023, 'assets/com2.jpg'), (2024, 'assets/vinyl.png')], default='assets/vinyl.png', max_length=200),
        ),
    ]
