# Generated by Django 4.2.6 on 2024-05-19 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_curriculum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='com',
            name='link',
        ),
    ]
