# Generated by Django 4.2.6 on 2024-05-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_remove_com_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='com',
            name='link',
            field=models.URLField(default='https://example.com'),
        ),
    ]
