# Generated by Django 4.2.6 on 2024-06-01 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_remove_com_link_com_preview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curriculum',
        ),
    ]
