# Generated by Django 4.2.6 on 2024-07-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_alter_com_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='com',
            name='version',
            field=models.CharField(blank=True, choices=[('Original', 'Original'), ('Remake', 'Remake'), ('Alternative Version', 'Alternative Version')], max_length=128, null=True),
        ),
    ]
