# Generated by Django 4.2.6 on 2024-10-31 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_alter_com_version'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='Web',
        ),
        migrations.AddField(
            model_name='com',
            name='genre',
            field=models.CharField(choices=[('Rock', 'Rock'), ('Jazz', 'Jazz'), ('Pop', 'Pop'), ('Orchestral', 'Orchestral')], default='Pop', max_length=32),
        ),
    ]
