# Generated by Django 5.1.6 on 2025-02-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_delete_data_delete_web_com_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='com',
            name='year',
            field=models.IntegerField(choices=[(2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025')]),
        ),
    ]
