# Generated by Django 5.1.6 on 2025-04-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_alter_com_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='com',
            name='year',
            field=models.IntegerField(default=2025, editable=False),
        ),
    ]
