# Generated by Django 5.2 on 2025-04-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0019_alter_com_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='com',
            name='title',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='com',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
